# Generated by Django 3.2.23 on 2024-01-10 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trash', to=settings.AUTH_USER_MODEL),
        ),
    ]
