# Generated by Django 3.2.23 on 2024-01-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_trash_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comments'),
        ),
    ]
