# Generated by Django 3.2.19 on 2023-06-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20230607_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='item',
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_price', to='auctions.bids'),
        ),
    ]
