# Generated by Django 3.2.19 on 2023-06-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20230608_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='price',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
