# Generated by Django 3.2.23 on 2024-01-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20240108_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
