# Generated by Django 3.2.23 on 2024-01-10 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listings_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_price', to='auctions.bids'),
        ),
    ]
