# Generated by Django 3.2.23 on 2024-01-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20240109_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
