# Generated by Django 3.2.23 on 2024-01-17 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comments_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comments'),
        ),
    ]
