# Generated by Django 3.2.23 on 2024-01-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_comments_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
